remote_theme: pmarsceill/just-the-docs
title: TuxJSQL hikaricp-cp
description: Tuxjsql SQLITE documentation
url: "https://tuxjsql.dev"
baseurl: "/hikaricp-cp/"
aux_links:
  "TuxJSQL Home":
    - "https://tuxjsql.dev"
  "TuxJSQL SQLITE GitHub":
    - "//github.com/tuxjsql/hikaricp-cp"
